const nodemailer = require('nodemailer');

const sendContactEmail = async (req, res) => {
    try {
        const { name, email, company, message } = req.body;

        if (!name || !email || !message) {
            return res.status(400).json({ success: false, error: 'Please provide name, email, and message.' });
        }

        // Configure Nodemailer transporter
        const transporter = nodemailer.createTransport({
            host: process.env.EMAIL_HOST,
            port: process.env.EMAIL_PORT,
            secure: false, // true for 465, false for other ports
            auth: {
                user: process.env.EMAIL_USER,
                pass: process.env.EMAIL_PASS
            }
        });

        // Email to Admin, CC to User
        const mailOptions = {
            from: `"${name}" <${process.env.EMAIL_USER}>`, // Send via authenticated email to avoid spam filters
            to: process.env.EMAIL_USER, // Admin email
            cc: email, // CC the user who submitted the form
            replyTo: email, // Allow admin to click reply and reply to user directly
            subject: `New Contact Request: ${name} from ${company || 'Unknown Company'}`,
            html: `
                <div style="font-family: Arial, sans-serif; line-height: 1.6; color: #333; max-w: 600px; margin: 0 auto; border: 1px solid #eaeaea; border-radius: 8px; overflow: hidden;">
                    <div style="background-color: #f06c3a; padding: 20px; text-align: center;">
                        <h2 style="color: white; margin: 0;">New Contact Form Submission</h2>
                    </div>
                    <div style="padding: 30px;">
                        <p style="font-size: 16px;">Hello,</p>
                        <p style="font-size: 16px;">You have received a new message from the HireNova contact form.</p>
                        <div style="background-color: #f9f9f9; padding: 20px; border-radius: 6px; margin: 20px 0;">
                            <p><strong>Name:</strong> ${name}</p>
                            <p><strong>Email:</strong> ${email}</p>
                            <p><strong>Company:</strong> ${company || 'N/A'}</p>
                            <h4 style="margin-bottom: 5px;">Message:</h4>
                            <p style="margin-top: 0; white-space: pre-wrap;">${message}</p>
                        </div>
                        <p style="color: #777; font-size: 12px; margin-top: 30px; text-align: center;">
                            This is an automated message generated by HireNova.<br/>
                            A copy of this email has been sent to ${email} for their records.
                        </p>
                    </div>
                </div>
            `
        };

        // Send Email
        await transporter.sendMail(mailOptions);

        res.status(200).json({
            success: true,
            data: 'Email sent successfully'
        });

    } catch (error) {
        console.error('Email send error:', error);
        res.status(500).json({ success: false, error: 'Failed to send email. Please try again later.' });
    }
};

module.exports = {
    sendContactEmail
};
